# Generated by Django 5.2.1 on 2025-06-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trusted_user',
            field=models.BooleanField(default=False),
        ),
    ]
