# Generated by Django 5.2.1 on 2025-07-15 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_trusted_user'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='billing.plan'),
        ),
        migrations.RemoveField(
            model_name='purchasedplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='purchasedplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PurchasedPlan',
        ),
    ]
