# Generated by Django 5.2.1 on 2025-05-28 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_contact_lists_alter_campaign_name_and_more'),
        ('mailer', '0002_alter_contact_options_alter_contactlist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opens_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('bounces_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='campaigns.campaign')),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_stats', to='mailer.contactlist')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('campaign', 'contact_list')},
            },
        ),
    ]
