# Generated by Django 5.2.1 on 2025-05-27 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0007_remove_senderemail_updated_at_and_more'),
        ('mail_templates', '0001_initial'),
        ('mailer', '0002_alter_contact_options_alter_contactlist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sending', 'Отправляется'), ('completed', 'Завершена')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('contact_lists', models.ManyToManyField(related_name='campaigns', to='mailer.contactlist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('sender_email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emails.senderemail')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail_templates.emailtemplate')),
            ],
        ),
    ]
