# Generated by Django 5.2.1 on 2025-05-28 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignstats'),
        ('mailer', '0002_alter_contact_options_alter_contactlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignstats',
            name='bounces_count',
        ),
        migrations.RemoveField(
            model_name='campaignstats',
            name='clicks_count',
        ),
        migrations.RemoveField(
            model_name='campaignstats',
            name='opens_count',
        ),
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(max_length=100, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('bounce_reason', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tracking', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tracking', to='mailer.contact')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
