# Generated by Django 5.2.1 on 2025-06-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_options_remove_campaign_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
