# Generated by Django 5.2.1 on 2025-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaign_name_alter_campaign_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='emails_failed',
            field=models.PositiveIntegerField(default=0, help_text='Количество неудачных отправок'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='emails_sent',
            field=models.PositiveIntegerField(default=0, help_text='Количество отправленных писем'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, help_text='Ожидаемое время завершения', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Процент выполнения'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_recipients',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество получателей'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Сообщение об ошибке при отправке'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, help_text='Время последней попытки', null=True),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество попыток отправки'),
        ),
    ]
