# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaign_name_alter_campaign_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID задачи Celery для отслеживания', max_length=255, null=True),
        ),
    ] 