# Generated by Django 5.2.1 on 2025-08-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_emails_failed_campaign_emails_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='emails_failed',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='emails_sent',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='estimated_completion',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='progress_percentage',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_recipients',
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='last_retry_at',
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='retry_count',
        ),
    ]
