# Generated by Django 5.2.1 on 2025-08-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_add_celery_task_id'),
        ('campaigns', '0009_remove_campaign_emails_failed_and_more'),
    ]

    operations = [
    ]
