# Generated by Django 5.2.1 on 2025-09-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_merge_20250801_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_per_minute', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки скорости отправки',
                'verbose_name_plural': 'Настройки скорости отправки',
            },
        ),
    ]
