# Generated by Django 5.2.1 on 2025-11-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_sendingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
