# Generated by Django 5.2.1 on 2025-07-15 08:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_plan_subscribers', models.PositiveIntegerField(default=100, help_text='Подписчиков для бесплатного тарифа')),
                ('free_plan_emails', models.PositiveIntegerField(default=1000, help_text='Писем для бесплатного тарифа')),
                ('free_plan_daily_limit', models.PositiveIntegerField(default=50, help_text='Дневной лимит для бесплатного тарифа')),
                ('currency', models.CharField(default='RUB', help_text='Валюта', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Налоговая ставка (%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Настройка биллинга',
                'verbose_name_plural': 'Настройки биллинга',
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип тарифа',
                'verbose_name_plural': 'Типы тарифов',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subscribers', models.PositiveIntegerField(default=0, help_text='Количество подписчиков')),
                ('emails_per_month', models.PositiveIntegerField(default=0, help_text='Количество писем в месяц')),
                ('max_emails_per_day', models.PositiveIntegerField(default=0, help_text='Максимум писем в день')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена в рублях', max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Процент скидки', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Рекомендуемый тариф')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='billing.plantype')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False, help_text='Автопродление')),
                ('payment_method', models.CharField(blank=True, help_text='Способ оплаты', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='ID транзакции', max_length=100)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Купленный тариф',
                'verbose_name_plural': 'Купленные тарифы',
                'ordering': ['-start_date'],
            },
        ),
    ]
