# Generated by Django 5.2.1 on 2025-08-03 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_cloudpayments_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingsettings',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='billingsettings',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='billingsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingsettings',
            name='free_plan_daily_limit',
            field=models.PositiveIntegerField(default=50, help_text='Дневной лимит писем в бесплатном тарифе'),
        ),
        migrations.AlterField(
            model_name='billingsettings',
            name='free_plan_subscribers',
            field=models.PositiveIntegerField(default=100, help_text='Количество подписчиков в бесплатном тарифе'),
        ),
        migrations.AlterField(
            model_name='billingsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
