# Generated by Django 5.2.1 on 2025-08-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_billingsettings_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedplan',
            name='cloudpayments_data',
            field=models.JSONField(blank=True, help_text='Данные от CloudPayments', null=True),
        ),
    ]
