# Generated by Django 5.2.1 on 2025-09-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_purchasedplan_cloudpayments_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsettings',
            name='free_plan_daily_limit',
            field=models.PositiveIntegerField(default=0, help_text='Дневной лимит писем в бесплатном тарифе (0 = неограниченно)'),
        ),
    ]
