# Generated by Django 5.2.1 on 2026-01-23 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_billingsettings_free_plan_daily_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Код, который вводит пользователь (регистр не важен)', max_length=50, unique=True, verbose_name='Промокод')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('max_activations', models.PositiveIntegerField(default=1, help_text='Сколько раз промокод можно использовать суммарно', verbose_name='Количество активаций')),
                ('used_activations', models.PositiveIntegerField(default=0, help_text='Сколько раз промокод уже был активирован', verbose_name='Уже использовано')),
                ('expires_at', models.DateTimeField(blank=True, help_text='До какой даты и времени действует промокод. Если не заполнено — бессрочный.', null=True, verbose_name='Срок действия')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='На сколько дней выдать тариф пользователю. 0 — практически бессрочно (20 лет).', verbose_name='Длительность тарифа в днях')),
                ('is_active', models.BooleanField(default=True, help_text='Можно ли сейчас использовать этот промокод', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('plan', models.ForeignKey(help_text='Тариф, который будет выдан пользователю при активации промокода', on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='billing.plan', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата активации')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='billing.promocode', verbose_name='Промокод')),
                ('purchased_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_activations', to='billing.purchasedplan', verbose_name='Выданный тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_activations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активация промокода',
                'verbose_name_plural': 'Активации промокодов',
                'ordering': ['-activated_at'],
            },
        ),
    ]
