# Generated by Django 5.2.1 on 2025-05-27 04:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_senderemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderemail',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='senderemail',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='senderemail',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='emails.domain'),
        ),
    ]
