# Generated by Django 5.2.1 on 2025-05-25 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['email']},
        ),
        migrations.AlterModelOptions(
            name='contactlist',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('valid', 'Действительный'), ('invalid', 'Недействительный'), ('blacklist', 'В чёрном списке')], default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
