# Generated by Django 5.2.1 on 2025-08-01 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_alter_contact_options_alter_contactlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('valid', 'Действительный'), ('invalid', 'Недействительный'), ('blacklist', 'В черном списке')], default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('total_emails', models.IntegerField(default=0)),
                ('processed_emails', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('invalid_count', models.IntegerField(default=0)),
                ('blacklisted_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_tasks', to='mailer.contactlist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
