# Generated by Django 5.2.1 on 2025-11-07 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_alter_importtask_id_to_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtask',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
