# Generated by Django 5.2.1 on 2025-06-08 10:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='ck_content',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=ckeditor.fields.RichTextField(help_text='HTML-контент, используется для рендеринга письма'),
        ),
    ]
