# Generated by Django 5.2.1 on 2025-06-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_templates', '0002_remove_emailtemplate_ck_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='ck_content',
            field=models.TextField(blank=True, help_text='Исходный контент из CKEditor (если нужен отдельно)'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=models.TextField(help_text='HTML-контент, используется для рендеринга письма'),
        ),
    ]
