# Generated by Django 5.2.1 on 2025-08-03 03:47

import apps.mail_templates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_templates', '0003_emailtemplate_ck_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загруженное изображение', upload_to=apps.mail_templates.models.template_image_upload_path)),
                ('filename', models.CharField(help_text='Оригинальное имя файла', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Размер файла в байтах')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Ширина изображения в пикселях', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Высота изображения в пикселях', null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Альтернативный текст для изображения', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Когда изображение загружено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Изображение шаблона',
                'verbose_name_plural': 'Изображения шаблонов',
                'ordering': ['-created_at'],
            },
        ),
    ]
