# Generated by Django 5.2.1 on 2025-11-13 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_templates', '0005_add_indexes_for_performance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailtemplate',
            name='mail_templ_owner_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailtemplate',
            name='mail_templ_owner_draft_idx',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
