# Generated by Django 5.2.1 on 2025-06-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignmoderation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Модерация кампании', 'verbose_name_plural': 'Модерация кампаний'},
        ),
    ]
