# Generated by Django 5.2.1 on 2025-07-20 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='author',
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_subject', models.CharField(max_length=255)),
                ('ticket_description', models.TextField()),
                ('ticket_status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('waiting', 'Ожидает ответа'), ('resolved', 'Решён'), ('closed', 'Закрыт')], default='open', max_length=20)),
                ('ticket_priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=20)),
                ('ticket_created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_closed_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_user_agent', models.TextField(blank=True)),
                ('ticket_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ticket_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportcategory')),
                ('ticket_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ticket_created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('message_internal', models.BooleanField(default=False)),
                ('message_staff_reply', models.BooleanField(default=False)),
                ('message_created_at', models.DateTimeField(auto_now_add=True)),
                ('message_updated_at', models.DateTimeField(auto_now=True)),
                ('message_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('message_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to='support.supportticket')),
            ],
            options={
                'ordering': ['message_created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('attachment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_file', models.FileField(upload_to='support_attachments/')),
                ('attachment_filename', models.CharField(max_length=255)),
                ('attachment_file_size', models.PositiveIntegerField()),
                ('attachment_mime_type', models.CharField(max_length=100)),
                ('attachment_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attachment_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to='support.supportmessage')),
                ('attachment_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='support.supportticket')),
            ],
        ),
        migrations.DeleteModel(
            name='TicketCategory',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketAttachment',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
