# Generated by Django 5.2.1 on 2025-08-20 03:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportcategory_remove_ticket_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChat',
            fields=[
                ('chat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('waiting', 'Ожидает ответа'), ('resolved', 'Решён'), ('closed', 'Закрыт')], default='open', max_length=20)),
                ('chat_created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_updated_at', models.DateTimeField(auto_now=True)),
                ('chat_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_chats', to=settings.AUTH_USER_MODEL)),
                ('chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-chat_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('message_staff_reply', models.BooleanField(default=False)),
                ('message_created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='support.supportchat')),
                ('message_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['message_created_at'],
            },
        ),
    ]
