# Generated by Django 5.2.1 on 2025-05-26 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='Например: example.com', max_length=253)),
                ('is_verified', models.BooleanField(default=False, help_text='Общий флаг: все DNS-записи пройдены')),
                ('dkim_verified', models.BooleanField(default=False, help_text='DKIM TXT-запись пройдена')),
                ('spf_verified', models.BooleanField(default=False, help_text='SPF TXT-запись пройдена')),
                ('verification_token', models.CharField(help_text='Уникальный токен для DNS-подтверждения', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Домен',
                'verbose_name_plural': 'Домены',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'domain_name')},
            },
        ),
        migrations.CreateModel(
            name='SenderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Например: user@example.com', max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Подтвержден ли адрес (click-письмо)')),
                ('verification_token', models.CharField(help_text='Уникальный токен для подтверждения email', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_emails', to='emails.domain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sender Email',
                'verbose_name_plural': 'Sender Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
