# Generated by Django 5.2.1 on 2025-05-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_domain_options_alter_domain_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='verification_token',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
