# Generated by Django 5.2.1 on 2025-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_remove_senderemail_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderemail',
            name='reply_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='senderemail',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
