# Generated by Django 5.2.1 on 2025-07-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_senderemail_reply_to_senderemail_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='dkim_selector',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='domain',
            name='private_key_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='domain',
            name='public_key',
            field=models.TextField(blank=True),
        ),
    ]
