# Generated by Django 5.2.1 on 2025-07-30 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_domain_dkim_selector_domain_private_key_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('owner', 'domain_name')},
        ),
    ]
