# Generated by Django 5.2.1 on 2025-09-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_alter_domain_domain_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='dmarc_policy',
            field=models.CharField(choices=[('none', 'None'), ('quarantine', 'Quarantine'), ('reject', 'Reject')], default='quarantine', max_length=20),
        ),
    ]
