# Generated by Django 5.2.1 on 2025-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_alter_domain_dmarc_default_and_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='dkim_selector',
            field=models.CharField(default='vashsender', max_length=100),
        ),
    ]
